wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.5
    cli_version: 0.17.8
    framework: huggingface
    huggingface_version: 4.44.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1727017193
    t:
      1:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 51
      - 55
      - 71
      - 79
      - 103
      - 105
      2:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 51
      - 55
      - 71
      - 79
      - 103
      - 105
      3:
      - 13
      - 23
      4: 3.12.5
      5: 0.17.8
      6: 4.44.2
      8:
      - 5
      13: linux-x86_64
