args:
    image2video: True # True for image2video, False for text2video
    latent_channels: 16
    mode: inference
    load: "/mnt/mir/fan23j/test/CogVideo/sat/ckpts_5b/5b-i2v-segm-fps-30-11-05-11-51" # This is for Full model without lora adapter
    # load: "{your lora folder} such as zRzRzRzRzRzRzR/lora-disney-08-20-13-28" # This is for Full model without lora adapter
    batch_size: 1
    input_type: txt
    input_file: configs/test.txt
    sampling_image_size: [480, 720]
    sampling_num_frames: 13 # Must be 13, 11 or 9
    sampling_fps: 30
    noised_image_input: True
    noise_last_frame: True
    #  fp16: True # For CogVideoX-2B
    bf16: True # For CogVideoX-5B and CoGVideoX-5B-I2V
    output_dir: results/ckpts_5b/5b-i2v-segm-fps-30-11-05-11-51
    force_inference: True
