args:
  latent_channels: 16
  mode: inference
  load: "/mnt/bum/hanyi/repo/CogVideo/sat/ckpts_2b_lora/2b_lora_17k_iter-09-13-17-04" # This is for Full model without lora adapter
  # load: "{your lora folder} such as zRzRzRzRzRzRzR/lora-disney-08-20-13-28" # This is for Full model without lora adapter

  batch_size: 1
  input_type: txt
  input_file: configs/test.txt
  sampling_num_frames: 13  # Must be 13, 11 or 9
  sampling_fps: 8
  fp16: True # For CogVideoX-2B
  # bf16: True # For CogVideoX-5B
  output_dir: results/2b_17k_iter
  force_inference: True